<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>cv4pve-botgram</AssemblyName>
		<Product>Corsinvest for Proxmox VE Telegram Bot</Product>
		<AssemblyTitle>Corsinvest for Proxmox VE Telegram Bot</AssemblyTitle>
		<Description>Telegram bot for Proxmox VE: manage and monitor your cluster via Telegram</Description>
		<ApplicationIcon>..\..\icon.ico</ApplicationIcon>
		<IsPackable>false</IsPackable>
		<InvariantGlobalization>true</InvariantGlobalization>
		<PredefinedCulturesOnly>false</PredefinedCulturesOnly>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Corsinvest.ProxmoxVE.Api.Console" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Corsinvest.ProxmoxVE.TelegramBot.Api\Corsinvest.ProxmoxVE.TelegramBot.Api.csproj" />
	</ItemGroup>
</Project>